Repository power-meter/android-client, pull requests merged in 2019-12, with the labels that each got.

#29 [PM-13] Add new exercises
  app/src/main/java/io/mochahub/powermeter/MainActivity.kt
  app/src/main/java/io/mochahub/powermeter/exercises/ExerciseFragment.kt
  app/src/main/java/io/mochahub/powermeter/exercises/NewExerciseDialog.kt
  app/src/main/java/io/mochahub/powermeter/exercises/NewExerciseSharedViewModel.kt
  app/src/main/java/io/mochahub/powermeter/models/Exercise.kt
  app/src/main/java/io/mochahub/powermeter/stats/StatsViewModel.kt
  app/src/main/res/drawable/ic_close_white_24dp.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/dialog_new_exercise.xml
  app/src/main/res/menu/menu_new_exercise.xml
  app/src/main/res/navigation/navigation.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: enhancement

#30 Refactor
  app/src/main/java/io/mochahub/powermeter/workoutsession/WorkoutSessionAdapter.kt
  app/src/main/java/io/mochahub/powermeter/workoutsession/WorkoutSessionFragment.kt
  app/src/main/java/io/mochahub/powermeter/workoutsession/WorkoutSessionViewModel.kt
  app/src/main/res/layout/fragment_workout_session.xml
  app/src/main/res/layout/row_workout_session.xml
  app/src/main/res/navigation/navigation.xml
Labels: refactor

#31 Epox-ify Exercises
  app/build.gradle
  app/src/main/java/io/mochahub/powermeter/exercises/ExerciseAdapter.kt
  app/src/main/java/io/mochahub/powermeter/exercises/ExerciseController.kt
  app/src/main/java/io/mochahub/powermeter/exercises/ExerciseFragment.kt
  app/src/main/java/io/mochahub/powermeter/exercises/ExerciseRowModel.kt
  app/src/main/java/io/mochahub/powermeter/shared/KotlinEpoxyHolder.kt
  app/src/main/res/layout/fragment_exercise.xml
  app/src/main/res/layout/row_exercise.xml
  build.gradle
Labels: refactor

#33 Fab & Fab Icon change
  app/src/main/res/drawable/ic_add_white_24dp.xml
  app/src/main/res/layout/fragment_exercise.xml
  app/src/main/res/layout/fragment_workout_session.xml
Labels: enhancement

#34 Readme update
  readme.md
Labels: documentation
